export const BookList = [
  { "title": "The Great Gatsby", "characteristics": [9, 8, 7] },
  { "title": "Crime and Punishment", "characteristics": [7, 9, 8] },
  { "title": "To Kill a Mockingbird", "characteristics": [8, 7, 9] },
  { "title": "1984", "characteristics": [8, 9, 7] },
  { "title": "Pride and Prejudice", "characteristics": [9, 7, 8] },
  { "title": "The Catcher in the Rye", "characteristics": [7, 8, 6] },
  { "title": "One Hundred Years of Solitude", "characteristics": [8, 9, 9] },
  { "title": "The Lord of the Rings", "characteristics": [9, 8, 8] },
  { "title": "The Chronicles of Narnia", "characteristics": [8, 7, 7] },
  { "title": "Harry Potter and the Sorcerer's Stone", "characteristics": [9, 8, 7] },
  { "title": "The Hobbit", "characteristics": [8, 7, 8] },
  { "title": "Moby-Dick", "characteristics": [7, 9, 8] },
  { "title": "The Kite Runner", "characteristics": [8, 7, 9] },
  { "title": "The Grapes of Wrath", "characteristics": [7, 8, 7] },
  { "title": "The Sound and the Fury", "characteristics": [6, 9, 8] },
  { "title": "Les Misérables", "characteristics": [8, 8, 9] },
  { "title": "The Picture of Dorian Gray", "characteristics": [9, 7, 8] },
  { "title": "The Count of Monte Cristo", "characteristics": [8, 9, 7] },
  { "title": "The Scarlet Letter", "characteristics": [7, 8, 6] },
  { "title": "Frankenstein", "characteristics": [7, 7, 9] },
  { "title": "The Silence of the Lambs", "characteristics": [7, 8, 9] },
  { "title": "The Godfather", "characteristics": [8, 9, 7] },
  { "title": "The Color Purple", "characteristics": [9, 8, 7] },
  { "title": "The Martian", "characteristics": [8, 7, 8] },
  { "title": "The Book Thief", "characteristics": [7, 9, 8] },
  { "title": "The Old Man and the Sea", "characteristics": [6, 8, 7] },
  { "title": "The Jungle", "characteristics": [7, 7, 9] },
  { "title": "The Fault in Our Stars", "characteristics": [8, 7, 8] },
  { "title": "The Brothers Karamazov", "characteristics": [9, 8, 7] },
  { "title": "The Odyssey", "characteristics": [8, 7, 9] }
];